### ISSUE TITLE
Add Citation.cff 

### ISSUE THREAD

**Issue by jlaura** [stac-extensions/scientific#9] opened 2023-09-28 15:45 UTC
[Citation.cff](https://citation-file-format.github.io) is a standardized format for human/machine readable citations. The scientific extensions should consider making use of a CFF file, either as a best practice to include a link to the CFF file or as a field within the extension.

**Comment by m-mohr** [comment] 2023-09-28 17:33
Duplicate of #8 :-)

**Closed as not planned by m-mohr** 2023-09-28 17:33 UTC
